### ISSUE TITLE
python wrapper not properly installed

### ISSUE THREAD

**Issue by giuspugl** [hpc4cmb/libconviqt#12]
Hello, 
trying to install libconviqt on Perlmutter , followed these steps : 
to avoid conflicting modules, i loaded only the necessary ones :  
 ```
module purge 
module load PrgEnv-gnu/8.3.3 
module load python 
module use /global/common/software/m3169/perlmutter/modulefiles 
module load openmpi 

``` 
then i 've installed cfitsio and libconviqt with the steps as in the README 
``` 
 ./autogen.sh  
  ./configure  --prefix=/pscratch/sd/g/giuspugl/software_pkgs/ --with-cfitsio=/path/to/cfitsiolib
 make && make check && make install 
``` 
 after installing the wrapper (that seems to be successfully done) ,  , i.e. : 
``` 
   cd python/
   python setup.py install
```
i get an error when running the test suite: 
``` 
   python setup.py test
```

 ``` 

ImportError: Failed to import test module: tests.test_libconviqt
Traceback (most recent call last):
  File "/pscratch/sd/g/giuspugl/software_pkgs/litebird/lib/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pscratch/sd/g/giuspugl/software_pkgs/litebird/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/pscratch/sd/g/giuspugl/software/libconviqt/python/tests/test_libconviqt.py", line 19, in <module>
    class ConviqtTest(TestCase):
  File "/pscratch/sd/g/giuspugl/software/libconviqt/python/tests/test_libconviqt.py", line 46, in ConviqtTest
    beam = conviqt.Beam(beamlmax, beammmax, pol, beamfile, comm)
           ^^^^^^^^^^^^
AttributeError: module 'libconviqt_wrapper' has no attribute 'Beam'
```  
Also, when reinstalling TOAST with libconviqt installed, it seems that conviqt is not successfully linked as the tests in `test_ops_sim_tod_conviqt` are not passing because libconviqt isn't available. Thus it seems that the wrapper's not properly  installed. 

could you please check what's wrong ?

**Comment by giuspugl** [comment]
Thanks to @keskitalo , the problem was in leaving unset the environment variable `LD_LIBRARY_PATH` .
